apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: segments
spec:
  type: secretstores.gcp.secretmanager
  version: v1
  metadata:
    - name: projectId
      value: prj-sie-fin-financiero-dev
