apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: app-shell-mfe-hc
  namespace: app-shell
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: TCP
      tcpHealthCheck:
        port: 80
  targetRef:
    group: ""
    kind: Service
    name: app-shell
