apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: accounting
spec:
  type: pubsub.gcp.pubsub
  version: v1
  metadata:
    - name: projectId
      value: prj-sie-fin-financiero-dev
    - name: disableEntityManagement
      value: "true"
