apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reconcile-company-base-taxes
  namespace: liquid-tax
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 1h"
